name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Get packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Assemble app debug APK
        run: |
          pushd android
          flutter build apk
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=test/main_test.dart
          popd
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: /build/app/outputs/apk/debug/app-debug.apk