name: Test two actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        if: ${{ github.event.pull_request.number }}
        run: echo "With number"
      
      - name: Slack Notification
        if: ${{ !github.event.pull_request.number }}
        run: echo "Without number 2"
  