name: Test Android cache CI

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: [ ubuntu-latest ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Do echos
        run: |
          echo github.base_ref: ${{ github.event.pull_request.base.ref }}