name: Test iOS cache CI

on:
  workflow_dispatch:
  push:
    branches: [ test-cache ]

jobs:
  build:
    runs-on: [ macos-latest ]
    env:
      FLUTTER_VERSION: '3.0.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get cached Flutter
        uses: actions/cache@v3
        with:
          path: |
            '/Users/runner/hostedtoolcache/flutter'
            '/Users/runner/work/_temp/**'
          key: ${{ runner.os }}-test-cache-${{ env.FLUTTER_VERSION }}
      - name: Checkout Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - name: 'Get Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'