name: Test cache CI

on:
  push:
    branches: [develop, master]

env:
  flutter_version: '3.0.0'

jobs:
  test:
    name: Run analyze and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test