name: Web CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Flutter version  
        run: flutter --version
      - name: Get packages
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze
      - name: Unit testing
        run: flutter test
      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '102.0.5005.61'
      - name: Start Chrome driver
        run: |
          export DISPLAY=:99
          chromedriver --port=4444 &
      - name: Integration testing
        run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/main_test.dart \
            -d web-server